### ISSUE TITLE
Release 版本加个签名啊

### ISSUE THREAD

**Issue by olbb** [tanjinc/AutoTool#5]
INSTALL_PARSE_FAILED_NO_CERTIFICATES

**Comment by tanjinc** [comment]
签过啊

**Comment by olbb** [comment]
确实没有啊  你检查下meta-info 里面连cert文件都没有

**Comment by tanjinc** [comment]
提交了一个release版本，你在看看

**Comment by tanjinc** [comment]
> 确实没有啊 你检查下meta-info 里面连cert文件都没有

确实，之前用v2签名不行，重新用v1签了，在最新release
